### ISSUE TITLE
std::error::Error is not implemented by any of the error types

### ISSUE THREAD

**Issue by autumnull** [IntrepidPig/mexprp#14]
None of the error types implement `std::error::Error`, so they cannot be used in the ways that you'd normally like to use an error, and aren't compatible with other error-handling libraries such as [anyhow](https://docs.rs/anyhow/1.0.42/anyhow/).

**Comment by autumnull** [comment]
I've looked into this more and I suggest using [thiserror](https://github.com/dtolnay/thiserror) instead of `failure`.

A short comparison of the two can be found [here](https://github.com/dtolnay/anyhow#comparison-to-failure), but I think this should make the library more flexible. I also found this more detailed [blog post](https://nick.groenen.me/posts/rust-error-handling/) detailing how to use `thiserror`.

**Comment by IntrepidPig** [comment]
`thiserror` is definitely my choice these days. This change was surprisingly painless, fixed in 7d396a7.
