### ISSUE TITLE
floor() of rug::Complex gives sin()

### ISSUE THREAD

**Issue by autumnull** [IntrepidPig/mexprp#17]
calling `floor()` on a rug::Complex number gives the sin of that number instead, because of this line here where it calls `Complex::sin_ref()`.

https://github.com/IntrepidPig/mexprp/blob/84101f619fef2fd6c21c279d3085743393f717d4/src/num/rugcomplex.rs#L115-L119

**Comment by IntrepidPig** [comment]
Fixed in fe5becf
